---
- hosts: all
  gather_facts: no
  connection: local
  user: vyos
  vars:
    cli:
      host: 10.200.83.224
      username: vyos
      password: vyos
      transport: cli

  tasks:
   - name: ping stuff
     ping:


   - name: Show commands
     vyos_command:
       commands:
          - show version
          - show hardware cpu
          - show interfaces
       provider: "{{ cli }}"


   - name: configures vyos hostname
     vyos_config:
       lines:
          - set system host-name {{ inventory_hostname }}
       provider: "{{ cli }}"
~
